name: AWS Connection Test
on:
  push:
    branches: [ main ] # This runs every time you push to the main branch

permissions:
  id-token: write   # This is required for the OIDC handshake
  contents: read    # This allows GitHub to read your code

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify Login
        run: aws sts get-caller-identity